x-paddler-common: &paddler-common
  image: paddler:v2.0.0
  build: ..

services:
  paddler-balancer:
    <<: *paddler-common
    container_name: paddler-balancer
    ports:
      - "8062:8062"  # Paddler management dashboard
    command: [
      "balancer",
      "--management-addr", "0.0.0.0:8060",
      "--inference-addr", "0.0.0.0:8061",
      "--web-admin-panel-addr", "0.0.0.0:8062"
    ]

  paddler-agent1:
    <<: *paddler-common
    container_name: paddler-agent1
    depends_on:
      - paddler-balancer
    command: [
      "agent",
      "--name", "llm-1",
      "--management-addr", "paddler-balancer:8060"
    ]

  paddler-agent2:
    <<: *paddler-common
    container_name: paddler-agent2
    depends_on:
      - paddler-balancer
    command: [
      "agent",
      "--name", "llm-2",
      "--management-addr", "paddler-balancer:8060"
    ]

volumes:
  hf-cache:
